[cursor]
  style = { shape = "Underline" }
  thickness = 0.3

[mouse]
  hide_when_typing = true

[[keyboard.bindings]]
  key = "Q"
  mods = "Control"
  action = "Quit"

[[keyboard.bindings]]
  key = "V"
  mods = "Alt"
  action = "ToggleViMode"

[[keyboard.bindings]]
  key = "T"
  mods = "Control"
  action = "CreateNewTab"

[font]
size = 9

[window]
decorations = "None"
opacity = 0.9

[window.dimensions]
columns = 160
lines = 32

[window.position]
x = 80
y = 20
